// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eden_western_food.Models;

#nullable disable

namespace eden_western_food.Migrations
{
    [DbContext(typeof(EdenContext))]
    partial class EdenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("eden_food.Models.Category", b =>
                {
                    b.Property<string>("CatCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CatOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("eden_food.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArriveDt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusInd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("eden_food.Models.MenuItem", b =>
                {
                    b.Property<string>("CatCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.ToTable("MenuItem");
                });

            modelBuilder.Entity("eden_food.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("eden_food.Models.OrderItem", b =>
                {
                    b.HasOne("eden_food.Models.Customer", "Cust")
                        .WithMany("OrderItem")
                        .HasForeignKey("CustId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cust");
                });

            modelBuilder.Entity("eden_food.Models.Customer", b =>
                {
                    b.Navigation("OrderItem");
                });
#pragma warning restore 612, 618
        }
    }
}
